### ISSUE TITLE
Validating logstash-input-journald-0.0.2.gem

### ISSUE THREAD

**Issue by nnachefski** [logstash-plugins/logstash-input-journald#12]
I'm attempting to install logstash-input-journald on a RHEL 7 system.  It builds successfully, however, when i goto install the gem it hangs at 'Validating logstash-input-journald'.  See below:

```
[root@localhost logstash-input-journald]# gem build logstash-input-journald.gemspec
  Successfully built RubyGem
  Name: logstash-input-journald
  Version: 0.0.2
  File: logstash-input-journald-0.0.2.gem

[root@localhost logstash-input-journald]# /opt/logstash/bin/plugin install logstash-input-journald-0.0.2.gem

Validating logstash-input-journald-0.0.2.gem
```

Any tips on how to get this working?

**Comment by nnachefski** [comment]
Ok, it just took a really long time.  It eventually completed with a dep version failure for logstash-core 3.0.0.  I removed the upper version boundary for core and it built (and installed).

**Comment by vaijab** [comment]
This should be now fixed. I just released a new gem into rubygems with logstash >=2.0.0 support.

https://rubygems.org/gems/logstash-input-journald/versions/0.1.0
https://github.com/logstash-plugins/logstash-input-journald/releases/tag/v0.1.0
