### ISSUE TITLE
Release and push new rubygem? 

### ISSUE THREAD

**Issue by dforste** [logstash-plugins/logstash-input-journald#13]
Can we get a new release and pushed to rubygems.org? 

The version requirements have changed in master so a push should be able to close the only two other issues open.

**Comment by vaijab** [comment]
@dforste sure, I was supposed to do that last week. Will do it now.

**Comment by vaijab** [comment]
Done
https://rubygems.org/gems/logstash-input-journald/versions/0.1.0
https://github.com/logstash-plugins/logstash-input-journald/releases/tag/v0.1.0
