### ISSUE TITLE
Logstash v5 support?

### ISSUE THREAD

**Issue by jlambert121** [logstash-plugins/logstash-input-journald#19]
Currently this gem is locked at `"logstash-core-plugin-api", ">= 1.60", "<= 2.99"`, has it been tested with version 5 by anyone or are there any obvious/known issues that would prevent it from working with version 5?  I am not familiar with all that is changing with v5, but as we are looking at a from scratch deployment I always like to start with the latest versions since it will likely be released by the time we're ready for actual implementation.

**Comment by suyograo** [comment]
@jlambert121 Yes this plugin should work on LS 5.0
