### ISSUE TITLE
Remember last location

### ISSUE THREAD

**Issue by dasJ** [logstash-plugins/logstash-input-journald#3]
It would be quite useful if this plugin could remember the last location of the cursor and continue at this position when I restart logstash.

**Comment by stuart-warren** [comment]
This is not a plugin I'm actually using myself any longer so can't give any promise I'll get round to it.
Perhaps do something similar to the file input sincedb

https://github.com/logstash-plugins/logstash-input-file/blob/master/lib/logstash/inputs/file.rb
https://github.com/jordansissel/ruby-filewatch/blob/master/lib/filewatch/tail.rb#L190

**Comment by stuart-warren** [comment]
merged by #4
